<?php

namespace Database\Seeders;

use App\Models\MedicineCategory;
use Illuminate\Database\Seeder;

class MedicineCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = [
            // Analgesics / Pain Relievers
            ['name' => 'Acetaminophen', 'description' => 'Pain reliever and fever reducer'],
            ['name' => 'Acetaminophen 500mg', 'description' => 'Pain reliever 500mg tablet'],
            ['name' => 'Acetaminophen 650mg', 'description' => 'Pain reliever 650mg tablet'],
            ['name' => 'Acetaminophen 1000mg', 'description' => 'Pain reliever 1000mg tablet'],
            ['name' => 'Ibuprofen', 'description' => 'NSAID pain reliever'],
            ['name' => 'Ibuprofen 200mg', 'description' => 'NSAID 200mg tablet'],
            ['name' => 'Ibuprofen 400mg', 'description' => 'NSAID 400mg tablet'],
            ['name' => 'Ibuprofen 600mg', 'description' => 'NSAID 600mg tablet'],
            ['name' => 'Ibuprofen 800mg', 'description' => 'NSAID 800mg tablet'],
            ['name' => 'Aspirin', 'description' => 'Pain reliever and antiplatelet'],
            ['name' => 'Aspirin 75mg', 'description' => 'Low dose aspirin'],
            ['name' => 'Aspirin 100mg', 'description' => 'Low dose aspirin'],
            ['name' => 'Aspirin 325mg', 'description' => 'Regular strength aspirin'],
            ['name' => 'Aspirin 500mg', 'description' => 'Extra strength aspirin'],
            ['name' => 'Diclofenac', 'description' => 'NSAID for pain and inflammation'],
            ['name' => 'Diclofenac 50mg', 'description' => 'Diclofenac 50mg tablet'],
            ['name' => 'Naproxen', 'description' => 'NSAID pain reliever'],
            ['name' => 'Naproxen 250mg', 'description' => 'Naproxen 250mg tablet'],
            ['name' => 'Naproxen 500mg', 'description' => 'Naproxen 500mg tablet'],
            ['name' => 'Tramadol', 'description' => 'Opioid pain medication'],
            ['name' => 'Tramadol 50mg', 'description' => 'Tramadol 50mg capsule'],
            ['name' => 'Tramadol 100mg', 'description' => 'Tramadol 100mg tablet'],
            ['name' => 'Morphine', 'description' => 'Strong opioid pain medication'],
            ['name' => 'Codeine', 'description' => 'Opioid pain medication'],
            ['name' => 'Paracetamol', 'description' => 'Pain reliever (alternative name for Acetaminophen)'],
            ['name' => 'Panadol', 'description' => 'Brand name paracetamol'],
            ['name' => 'Panadol Extra', 'description' => 'Panadol with caffeine'],
            ['name' => 'Brufen', 'description' => 'Brand name ibuprofen'],
            ['name' => 'Nurofen', 'description' => 'Brand name ibuprofen'],
            ['name' => 'Cataflam', 'description' => 'Brand name diclofenac'],
            ['name' => 'Voltaren', 'description' => 'Brand name diclofenac'],
            ['name' => 'Celebrex', 'description' => 'COX-2 inhibitor'],
            ['name' => 'Mobic', 'description' => 'Brand name meloxicam'],
            ['name' => 'Movalis', 'description' => 'Brand name meloxicam'],
            ['name' => 'Lortab', 'description' => 'Hydrocodone/acetaminophen combination'],
            ['name' => 'Oxycodone', 'description' => 'Strong opioid pain medication'],
            ['name' => 'Hydrocodone', 'description' => 'Opioid pain medication'],
            ['name' => 'Fentanyl', 'description' => 'Strong opioid pain patch'],
            ['name' => 'Gabapentin', 'description' => 'Neuropathic pain medication'],
            ['name' => 'Pregabalin', 'description' => 'Neuropathic pain medication'],
            ['name' => 'Amitriptyline', 'description' => 'Tricyclic antidepressant for pain'],
            ['name' => 'Nortriptyline', 'description' => 'Tricyclic antidepressant'],
            ['name' => 'Duloxetine', 'description' => 'SNRI for pain and depression'],
            ['name' => 'PREGABALIN', 'description' => 'Neuropathic pain (capsule)'],

            // Antibiotics
            ['name' => 'Amoxicillin', 'description' => 'Penicillin antibiotic'],
            ['name' => 'Amoxicillin 250mg', 'description' => 'Amoxicillin 250mg capsule'],
            ['name' => 'Amoxicillin 500mg', 'description' => 'Amoxicillin 500mg capsule'],
            ['name' => 'Amoxicillin 875mg', 'description' => 'Amoxicillin 875mg tablet'],
            ['name' => 'Azithromycin', 'description' => 'Macrolide antibiotic'],
            ['name' => 'Azithromycin 250mg', 'description' => 'Azithromycin 250mg tablet'],
            ['name' => 'Azithromycin 500mg', 'description' => 'Azithromycin 500mg tablet'],
            ['name' => 'Ciprofloxacin', 'description' => 'Fluoroquinolone antibiotic'],
            ['name' => 'Ciprofloxacin 250mg', 'description' => 'Ciprofloxacin 250mg tablet'],
            ['name' => 'Ciprofloxacin 500mg', 'description' => 'Ciprofloxacin 500mg tablet'],
            ['name' => 'Ciprofloxacin 750mg', 'description' => 'Ciprofloxacin 750mg tablet'],
            ['name' => 'Levofloxacin', 'description' => 'Fluoroquinolone antibiotic'],
            ['name' => 'Levofloxacin 500mg', 'description' => 'Levofloxacin 500mg tablet'],
            ['name' => 'Metronidazole', 'description' => 'Antibiotic and antiprotozoal'],
            ['name' => 'Metronidazole 400mg', 'description' => 'Metronidazole 400mg tablet'],
            ['name' => 'Metronidazole 500mg', 'description' => 'Metronidazole 500mg tablet'],
            ['name' => 'Doxycycline', 'description' => 'Tetracycline antibiotic'],
            ['name' => 'Doxycycline 100mg', 'description' => 'Doxycycline 100mg capsule'],
            ['name' => 'Tetracycline', 'description' => 'Tetracycline antibiotic'],
            ['name' => 'Cefuroxime', 'description' => 'Second generation cephalosporin'],
            ['name' => 'Cefuroxime 250mg', 'description' => 'Cefuroxime 250mg tablet'],
            ['name' => 'Cefuroxime 500mg', 'description' => 'Cefuroxime 500mg tablet'],
            ['name' => 'Cefalexin', 'description' => 'First generation cephalosporin'],
            ['name' => 'Cefalexin 250mg', 'description' => 'Cefalexin 250mg capsule'],
            ['name' => 'Cefalexin 500mg', 'description' => 'Cefalexin 500mg capsule'],
            ['name' => 'Ceftriaxone', 'description' => 'Third generation cephalosporin injection'],
            ['name' => 'Ceftazidime', 'description' => 'Third generation cephalosporin'],
            ['name' => 'Cefotaxime', 'description' => 'Third generation cephalosporin'],
            ['name' => 'Meropenem', 'description' => 'Carbapenem antibiotic'],
            ['name' => 'Imipenem', 'description' => 'Carbapenem antibiotic'],
            ['name' => 'Vancomycin', 'description' => 'Glycopeptide antibiotic'],
            ['name' => 'Gentamicin', 'description' => 'Aminoglycoside antibiotic'],
            ['name' => 'Amikacin', 'description' => 'Aminoglycoside antibiotic'],
            ['name' => 'Streptomycin', 'description' => 'Aminoglycoside antibiotic'],
            ['name' => 'Clindamycin', 'description' => 'Lincosamide antibiotic'],
            ['name' => 'Clindamycin 150mg', 'description' => 'Clindamycin 150mg capsule'],
            ['name' => 'Clindamycin 300mg', 'description' => 'Clindamycin 300mg capsule'],
            ['name' => 'Sulfamethoxazole/Trimethoprim', 'description' => 'Sulfonamide antibiotic combination'],
            ['name' => 'Co-trimoxazole', 'description' => 'Antibiotic combination (Bactrim/Septra)'],
            ['name' => 'Nitrofurantoin', 'description' => 'Urinary antibiotic'],
            ['name' => 'Nitrofurantoin 100mg', 'description' => 'Nitrofurantoin 100mg capsule'],
            ['name' => 'Fosfomycin', 'description' => 'Urinary antibiotic'],
            ['name' => 'Cephalexin', 'description' => 'First generation cephalosporin'],
            ['name' => 'Augmentin', 'description' => 'Amoxicillin/clavulanate combination'],
            ['name' => 'Zinnat', 'description' => 'Brand name cefuroxime'],
            ['name' => 'Keflex', 'description' => 'Brand name cephalexin'],
            ['name' => 'Zithromax', 'description' => 'Brand name azithromycin'],
            ['name' => 'Sumamed', 'description' => 'Brand name azithromycin'],
            ['name' => 'Ciplox', 'description' => 'Brand name ciprofloxacin'],
            ['name' => 'Flagyl', 'description' => 'Brand name metronidazole'],

            // Cardiovascular / Blood Pressure
            ['name' => 'Lisinopril', 'description' => 'ACE inhibitor for blood pressure'],
            ['name' => 'Lisinopril 5mg', 'description' => 'Lisinopril 5mg tablet'],
            ['name' => 'Lisinopril 10mg', 'description' => 'Lisinopril 10mg tablet'],
            ['name' => 'Lisinopril 20mg', 'description' => 'Lisinopril 20mg tablet'],
            ['name' => 'Amlodipine', 'description' => 'Calcium channel blocker'],
            ['name' => 'Amlodipine 5mg', 'description' => 'Amlodipine 5mg tablet'],
            ['name' => 'Amlodipine 10mg', 'description' => 'Amlodipine 10mg tablet'],
            ['name' => 'Metoprolol', 'description' => 'Beta blocker'],
            ['name' => 'Metoprolol 25mg', 'description' => 'Metoprolol 25mg tablet'],
            ['name' => 'Metoprolol 50mg', 'description' => 'Metoprolol 50mg tablet'],
            ['name' => 'Metoprolol 100mg', 'description' => 'Metoprolol 100mg tablet'],
            ['name' => 'Atenolol', 'description' => 'Beta blocker'],
            ['name' => 'Atenolol 50mg', 'description' => 'Atenolol 50mg tablet'],
            ['name' => 'Atenolol 100mg', 'description' => 'Atenolol 100mg tablet'],
            ['name' => 'Carvedilol', 'description' => 'Alpha and beta blocker'],
            ['name' => 'Carvedilol 12.5mg', 'description' => 'Carvedilol 12.5mg tablet'],
            ['name' => 'Carvedilol 25mg', 'description' => 'Carvedilol 25mg tablet'],
            ['name' => 'Bisoprolol', 'description' => 'Beta blocker'],
            ['name' => 'Bisoprolol 5mg', 'description' => 'Bisoprolol 5mg tablet'],
            ['name' => 'Bisoprolol 10mg', 'description' => 'Bisoprolol 10mg tablet'],
            ['name' => 'Nebivolol', 'description' => 'Beta blocker'],
            ['name' => 'Ramipril', 'description' => 'ACE inhibitor'],
            ['name' => 'Ramipril 2.5mg', 'description' => 'Ramipril 2.5mg tablet'],
            ['name' => 'Ramipril 5mg', 'description' => 'Ramipril 5mg tablet'],
            ['name' => 'Ramipril 10mg', 'description' => 'Ramipril 10mg tablet'],
            ['name' => 'Enalapril', 'description' => 'ACE inhibitor'],
            ['name' => 'Enalapril 5mg', 'description' => 'Enalapril 5mg tablet'],
            ['name' => 'Enalapril 10mg', 'description' => 'Enalapril 10mg tablet'],
            ['name' => 'Losartan', 'description' => 'ARB for blood pressure'],
            ['name' => 'Losartan 25mg', 'description' => 'Losartan 25mg tablet'],
            ['name' => 'Losartan 50mg', 'description' => 'Losartan 50mg tablet'],
            ['name' => 'Losartan 100mg', 'description' => 'Losartan 100mg tablet'],
            ['name' => 'Valsartan', 'description' => 'ARB for blood pressure'],
            ['name' => 'Valsartan 80mg', 'description' => 'Valsartan 80mg tablet'],
            ['name' => 'Valsartan 160mg', 'description' => 'Valsartan 160mg tablet'],
            ['name' => 'Irbesartan', 'description' => 'ARB for blood pressure'],
            ['name' => 'Irbesartan 150mg', 'description' => 'Irbesartan 150mg tablet'],
            ['name' => 'Irbesartan 300mg', 'description' => 'Irbesartan 300mg tablet'],
            ['name' => 'Telmisartan', 'description' => 'ARB for blood pressure'],
            ['name' => 'Telmisartan 40mg', 'description' => 'Telmisartan 40mg tablet'],
            ['name' => 'Telmisartan 80mg', 'description' => 'Telmisartan 80mg tablet'],
            ['name' => 'Olmesartan', 'description' => 'ARB for blood pressure'],
            ['name' => 'Hydrochlorothiazide', 'description' => 'Diuretic'],
            ['name' => 'Hydrochlorothiazide 12.5mg', 'description' => 'HCTZ 12.5mg tablet'],
            ['name' => 'Hydrochlorothiazide 25mg', 'description' => 'HCTZ 25mg tablet'],
            ['name' => 'Furosemide', 'description' => 'Loop diuretic'],
            ['name' => 'Furosemide 20mg', 'description' => 'Furosemide 20mg tablet'],
            ['name' => 'Furosemide 40mg', 'description' => 'Furosemide 40mg tablet'],
            ['name' => 'Spironolactone', 'description' => 'Potassium-sparing diuretic'],
            ['name' => 'Spironolactone 25mg', 'description' => 'Spironolactone 25mg tablet'],
            ['name' => 'Spironolactone 50mg', 'description' => 'Spironolactone 50mg tablet'],
            ['name' => 'Amlodipine Besylate', 'description' => 'Calcium channel blocker'],
            ['name' => 'Norvasc', 'description' => 'Brand name amlodipine'],
            ['name' => 'Lotrel', 'description' => 'Amlodipine/benazepril combination'],
            ['name' => 'Cozaar', 'description' => 'Brand name losartan'],
            ['name' => 'Diovan', 'description' => 'Brand name valsartan'],
            ['name' => 'Benicar', 'description' => 'Brand name olmesartan'],
            ['name' => 'Micardis', 'description' => 'Brand name telmisartan'],
            ['name' => 'Avapro', 'description' => 'Brand name irbesartan'],
            ['name' => 'Toprol XL', 'description' => 'Brand name metoprolol'],
            ['name' => 'Zestril', 'description' => 'Brand name lisinopril'],
            ['name' => 'Prinivil', 'description' => 'Brand name lisinopril'],
            ['name' => 'Capoten', 'description' => 'Brand name captopril'],
            ['name' => 'Vasotec', 'description' => 'Brand name enalapril'],
            ['name' => 'Monopril', 'description' => 'Brand name fosinopril'],
            ['name' => 'Accupril', 'description' => 'Brand name quinapril'],
            ['name' => 'Altace', 'description' => 'Brand name ramipril'],
            ['name' => 'Cardizem', 'description' => 'Brand name diltiazem'],
            ['name' => 'Procardia', 'description' => 'Brand name nifedipine'],
            ['name' => 'Calan', 'description' => 'Brand name verapamil'],
            ['name' => 'Isordil', 'description' => 'Brand name isosorbide dinitrate'],
            ['name' => 'Ismo', 'description' => 'Brand name isosorbide mononitrate'],
            ['name' => 'Imdur', 'description' => 'Brand name isosorbide mononitrate'],
            ['name' => 'Nitroglycerin', 'description' => 'Nitrate for angina'],
            ['name' => 'Nitrostat', 'description' => 'Brand name nitroglycerin sublingual'],
            ['name' => 'Aspirin 81mg', 'description' => 'Low dose aspirin for heart protection'],
            ['name' => 'Clopidogrel', 'description' => 'Antiplatelet medication'],
            ['name' => 'Clopidogrel 75mg', 'description' => 'Clopidogrel 75mg tablet'],
            ['name' => 'Plavix', 'description' => 'Brand name clopidogrel'],
            ['name' => 'Warfarin', 'description' => 'Blood thinner'],
            ['name' => 'Warfarin 2.5mg', 'description' => 'Warfarin 2.5mg tablet'],
            ['name' => 'Warfarin 5mg', 'description' => 'Warfarin 5mg tablet'],
            ['name' => 'Rivaroxaban', 'description' => 'Direct oral anticoagulant'],
            ['name' => 'Rivaroxaban 20mg', 'description' => 'Rivaroxaban 20mg tablet'],
            ['name' => 'Apixaban', 'description' => 'Direct oral anticoagulant'],
            ['name' => 'Apixaban 5mg', 'description' => 'Apixaban 5mg tablet'],
            ['name' => 'Dabigatran', 'description' => 'Direct oral anticoagulant'],
            ['name' => 'Xarelto', 'description' => 'Brand name rivaroxaban'],
            ['name' => 'Eliquis', 'description' => 'Brand name apixaban'],
            ['name' => 'Pradaxa', 'description' => 'Brand name dabigatran'],
            ['name' => 'Atorvastatin', 'description' => 'Statin for cholesterol'],
            ['name' => 'Atorvastatin 10mg', 'description' => 'Atorvastatin 10mg tablet'],
            ['name' => 'Atorvastatin 20mg', 'description' => 'Atorvastatin 20mg tablet'],
            ['name' => 'Atorvastatin 40mg', 'description' => 'Atorvastatin 40mg tablet'],
            ['name' => 'Atorvastatin 80mg', 'description' => 'Atorvastatin 80mg tablet'],
            ['name' => 'Simvastatin', 'description' => 'Statin for cholesterol'],
            ['name' => 'Simvastatin 10mg', 'description' => 'Simvastatin 10mg tablet'],
            ['name' => 'Simvastatin 20mg', 'description' => 'Simvastatin 20mg tablet'],
            ['name' => 'Simvastatin 40mg', 'description' => 'Simvastatin 40mg tablet'],
            ['name' => 'Rosuvastatin', 'description' => 'Statin for cholesterol'],
            ['name' => 'Rosuvastatin 10mg', 'description' => 'Rosuvastatin 10mg tablet'],
            ['name' => 'Rosuvastatin 20mg', 'description' => 'Rosuvastatin 20mg tablet'],
            ['name' => 'Pravastatin', 'description' => 'Statin for cholesterol'],
            ['name' => 'Lovastatin', 'description' => 'Statin for cholesterol'],
            ['name' => 'Lipitor', 'description' => 'Brand name atorvastatin'],
            ['name' => 'Zocor', 'description' => 'Brand name simvastatin'],
            ['name' => 'Crestor', 'description' => 'Brand name rosuvastatin'],
            ['name' => 'Mevacor', 'description' => 'Brand name lovastatin'],
            ['name' => 'Pravachol', 'description' => 'Brand name pravastatin'],

            // Diabetes
            ['name' => 'Metformin', 'description' => 'Biguanide for type 2 diabetes'],
            ['name' => 'Metformin 500mg', 'description' => 'Metformin 500mg tablet'],
            ['name' => 'Metformin 850mg', 'description' => 'Metformin 850mg tablet'],
            ['name' => 'Metformin 1000mg', 'description' => 'Metformin 1000mg tablet'],
            ['name' => 'Glipizide', 'description' => 'Sulfonylurea for diabetes'],
            ['name' => 'Glipizide 5mg', 'description' => 'Glipizide 5mg tablet'],
            ['name' => 'Glipizide 10mg', 'description' => 'Glipizide 10mg tablet'],
            ['name' => 'Glyburide', 'description' => 'Sulfonylurea for diabetes'],
            ['name' => 'Glyburide 5mg', 'description' => 'Glyburide 5mg tablet'],
            ['name' => 'Glimepiride', 'description' => 'Sulfonylurea for diabetes'],
            ['name' => 'Glimepiride 2mg', 'description' => 'Glimepiride 2mg tablet'],
            ['name' => 'Glimepiride 4mg', 'description' => 'Glimepiride 4mg tablet'],
            ['name' => 'Pioglitazone', 'description' => 'Thiazolidinedione for diabetes'],
            ['name' => 'Pioglitazone 15mg', 'description' => 'Pioglitazone 15mg tablet'],
            ['name' => 'Pioglitazone 30mg', 'description' => 'Pioglitazone 30mg tablet'],
            ['name' => 'Sitagliptin', 'description' => 'DPP-4 inhibitor for diabetes'],
            ['name' => 'Sitagliptin 50mg', 'description' => 'Sitagliptin 50mg tablet'],
            ['name' => 'Sitagliptin 100mg', 'description' => 'Sitagliptin 100mg tablet'],
            ['name' => 'Linagliptin', 'description' => 'DPP-4 inhibitor for diabetes'],
            ['name' => 'Linagliptin 5mg', 'description' => 'Linagliptin 5mg tablet'],
            ['name' => 'Saxagliptin', 'description' => 'DPP-4 inhibitor for diabetes'],
            ['name' => 'Vildagliptin', 'description' => 'DPP-4 inhibitor for diabetes'],
            ['name' => 'Canagliflozin', 'description' => 'SGLT2 inhibitor for diabetes'],
            ['name' => 'Dapagliflozin', 'description' => 'SGLT2 inhibitor for diabetes'],
            ['name' => 'Empagliflozin', 'description' => 'SGLT2 inhibitor for diabetes'],
            ['name' => 'Acarbose', 'description' => 'Alpha-glucosidase inhibitor'],
            ['name' => 'Miglitol', 'description' => 'Alpha-glucosidase inhibitor'],
            ['name' => 'Repaglinide', 'description' => 'Meglitinide for diabetes'],
            ['name' => 'Nateglinide', 'description' => 'Meglitinide for diabetes'],
            ['name' => 'Glucophage', 'description' => 'Brand name metformin'],
            ['name' => 'Glucophage XR', 'description' => 'Extended release metformin'],
            ['name' => 'DiaBeta', 'description' => 'Brand name glyburide'],
            ['name' => 'Micronase', 'description' => 'Brand name glyburide'],
            ['name' => 'Glucotrol', 'description' => 'Brand name glipizide'],
            ['name' => 'Amaryl', 'description' => 'Brand name glimepiride'],
            ['name' => 'Actos', 'description' => 'Brand name pioglitazone'],
            ['name' => 'Januvia', 'description' => 'Brand name sitagliptin'],
            ['name' => 'Onglyza', 'description' => 'Brand name saxagliptin'],
            ['name' => 'Tradjenta', 'description' => 'Brand name linagliptin'],
            ['name' => 'Galvus', 'description' => 'Brand name vildagliptin'],
            ['name' => 'Invokana', 'description' => 'Brand name canagliflozin'],
            ['name' => 'Farxiga', 'description' => 'Brand name dapagliflozin'],
            ['name' => 'Jardiance', 'description' => 'Brand name empagliflozin'],
            ['name' => 'Precose', 'description' => 'Brand name acarbose'],
            ['name' => 'Glucovance', 'description' => 'Glyburide/metformin combination'],
            ['name' => 'Janumet', 'description' => 'Sitagliptin/metformin combination'],
            ['name' => 'Kombiglyze', 'description' => 'Saxagliptin/metformin combination'],
            ['name' => 'Jentadueto', 'description' => 'Linagliptin/metformin combination'],
            ['name' => 'Xigduo', 'description' => 'Dapagliflozin/metformin combination'],
            ['name' => 'Synjardy', 'description' => 'Empagliflozin/metformin combination'],

            // Gastrointestinal
            ['name' => 'Omeprazole', 'description' => 'Proton pump inhibitor'],
            ['name' => 'Omeprazole 20mg', 'description' => 'Omeprazole 20mg capsule'],
            ['name' => 'Omeprazole 40mg', 'description' => 'Omeprazole 40mg capsule'],
            ['name' => 'Pantoprazole', 'description' => 'Proton pump inhibitor'],
            ['name' => 'Pantoprazole 20mg', 'description' => 'Pantoprazole 20mg tablet'],
            ['name' => 'Pantoprazole 40mg', 'description' => 'Pantoprazole 40mg tablet'],
            ['name' => 'Esomeprazole', 'description' => 'Proton pump inhibitor'],
            ['name' => 'Esomeprazole 20mg', 'description' => 'Esomeprazole 20mg tablet'],
            ['name' => 'Esomeprazole 40mg', 'description' => 'Esomeprazole 40mg tablet'],
            ['name' => 'Lansoprazole', 'description' => 'Proton pump inhibitor'],
            ['name' => 'Lansoprazole 30mg', 'description' => 'Lansoprazole 30mg capsule'],
            ['name' => 'Rabeprazole', 'description' => 'Proton pump inhibitor'],
            ['name' => 'Dexlansoprazole', 'description' => 'Proton pump inhibitor'],
            ['name' => 'Ranitidine', 'description' => 'H2 blocker'],
            ['name' => 'Ranitidine 150mg', 'description' => 'Ranitidine 150mg tablet'],
            ['name' => 'Ranitidine 300mg', 'description' => 'Ranitidine 300mg tablet'],
            ['name' => 'Famotidine', 'description' => 'H2 blocker'],
            ['name' => 'Famotidine 20mg', 'description' => 'Famotidine 20mg tablet'],
            ['name' => 'Famotidine 40mg', 'description' => 'Famotidine 40mg tablet'],
            ['name' => 'Cimetidine', 'description' => 'H2 blocker'],
            ['name' => 'Nizatidine', 'description' => 'H2 blocker'],
            ['name' => 'Sucralfate', 'description' => 'Gastric ulcer protective'],
            ['name' => 'Misoprostol', 'description' => 'Prostaglandin for ulcers'],
            ['name' => 'Ondansetron', 'description' => 'Antiemetic'],
            ['name' => 'Ondansetron 4mg', 'description' => 'Ondansetron 4mg tablet'],
            ['name' => 'Ondansetron 8mg', 'description' => 'Ondansetron 8mg tablet'],
            ['name' => 'Metoclopramide', 'description' => 'Prokinetic for nausea'],
            ['name' => 'Metoclopramide 10mg', 'description' => 'Metoclopramide 10mg tablet'],
            ['name' => 'Domperidone', 'description' => 'Prokinetic for nausea'],
            ['name' => 'Prochlorperazine', 'description' => 'Antiemetic'],
            ['name' => 'Promethazine', 'description' => 'Antiemetic and antihistamine'],
            ['name' => 'Loperamide', 'description' => 'Anti-diarrheal'],
            ['name' => 'Loperamide 2mg', 'description' => 'Loperamide 2mg capsule'],
            ['name' => 'Diphenoxylate', 'description' => 'Anti-diarrheal'],
            ['name' => 'Lactulose', 'description' => 'Laxative'],
            ['name' => 'Polyethylene glycol', 'description' => 'Laxative (Miralax)'],
            ['name' => 'Bisacodyl', 'description' => 'Stimulant laxative'],
            ['name' => 'Senna', 'description' => 'Stimulant laxative'],
            ['name' => 'Docusate sodium', 'description' => 'Stool softener'],
            ['name' => 'Magnesium hydroxide', 'description' => 'Antacid and laxative'],
            ['name' => 'Magnesium citrate', 'description' => 'Laxative'],
            ['name' => 'Prilosec', 'description' => 'Brand name omeprazole'],
            ['name' => 'Nexium', 'description' => 'Brand name esomeprazole'],
            ['name' => 'Prevacid', 'description' => 'Brand name lansoprazole'],
            ['name' => 'Protonix', 'description' => 'Brand name pantoprazole'],
            ['name' => 'Aciphex', 'description' => 'Brand name rabeprazole'],
            ['name' => 'Dexilant', 'description' => 'Brand name dexlansoprazole'],
            ['name' => 'Zantac', 'description' => 'Brand name ranitidine'],
            ['name' => 'Pepcid', 'description' => 'Brand name famotidine'],
            ['name' => 'Tagamet', 'description' => 'Brand name cimetidine'],
            ['name' => 'Zofran', 'description' => 'Brand name ondansetron'],
            ['name' => 'Reglan', 'description' => 'Brand name metoclopramide'],
            ['name' => 'Imodium', 'description' => 'Brand name loperamide'],

            // Respiratory / Allergy / Asthma
            ['name' => 'Salbutamol', 'description' => 'Bronchodilator for asthma'],
            ['name' => 'Salbutamol 100mcg', 'description' => 'Salbutamol inhaler'],
            ['name' => 'Salbutamol 200mcg', 'description' => 'Salbutamol inhaler'],
            ['name' => 'Salbutamol 2.5mg', 'description' => 'Salbutamol nebulizer solution'],
            ['name' => 'Salbutamol 5mg', 'description' => 'Salbutamol nebulizer solution'],
            ['name' => 'Terbutaline', 'description' => 'Bronchodilator for asthma'],
            ['name' => 'Terbutaline 0.25mg', 'description' => 'Terbutaline injection'],
            ['name' => 'Terbutaline 2.5mg', 'description' => 'Terbutaline tablet'],
            ['name' => 'Formoterol', 'description' => 'Long-acting bronchodilator'],
            ['name' => 'Salmeterol', 'description' => 'Long-acting bronchodilator'],
            ['name' => 'Vilanterol', 'description' => 'Long-acting bronchodilator'],
            ['name' => 'Ipratropium', 'description' => 'Anticholinergic bronchodilator'],
            ['name' => 'Ipratropium 0.5mg', 'description' => 'Ipratropium nebulizer solution'],
            ['name' => 'Tiotropium', 'description' => 'Long-acting anticholinergic'],
            ['name' => 'Tiotropium 18mcg', 'description' => 'Tiotropium capsule for inhaler'],
            ['name' => 'Umeclidinium', 'description' => 'Long-acting anticholinergic'],
            ['name' => 'Fluticasone', 'description' => 'Inhaled corticosteroid'],
            ['name' => 'Fluticasone 100mcg', 'description' => 'Fluticasone inhaler'],
            ['name' => 'Fluticasone 250mcg', 'description' => 'Fluticasone inhaler'],
            ['name' => 'Fluticasone 500mcg', 'description' => 'Fluticasone inhaler'],
            ['name' => 'Budesonide', 'description' => 'Inhaled corticosteroid'],
            ['name' => 'Budesonide 100mcg', 'description' => 'Budesonide inhaler'],
            ['name' => 'Budesonide 200mcg', 'description' => 'Budesonide inhaler'],
            ['name' => 'Budesonide 400mcg', 'description' => 'Budesonide inhaler'],
            ['name' => 'Beclomethasone', 'description' => 'Inhaled corticosteroid'],
            ['name' => 'Ciclesonide', 'description' => 'Inhaled corticosteroid'],
            ['name' => 'Mometasone', 'description' => 'Inhaled corticosteroid'],
            ['name' => 'Montelukast', 'description' => 'Leukotriene receptor antagonist'],
            ['name' => 'Montelukast 4mg', 'description' => 'Montelukast 4mg chewable'],
            ['name' => 'Montelukast 5mg', 'description' => 'Montelukast 5mg chewable'],
            ['name' => 'Montelukast 10mg', 'description' => 'Montelukast 10mg tablet'],
            ['name' => 'Zafirlukast', 'description' => 'Leukotriene receptor antagonist'],
            ['name' => 'Zileuton', 'description' => '5-lipoxygenase inhibitor'],
            ['name' => 'Cetirizine', 'description' => 'Second generation antihistamine'],
            ['name' => 'Cetirizine 5mg', 'description' => 'Cetirizine 5mg tablet'],
            ['name' => 'Cetirizine 10mg', 'description' => 'Cetirizine 10mg tablet'],
            ['name' => 'Loratadine', 'description' => 'Second generation antihistamine'],
            ['name' => 'Loratadine 10mg', 'description' => 'Loratadine 10mg tablet'],
            ['name' => 'Desloratadine', 'description' => 'Second generation antihistamine'],
            ['name' => 'Desloratadine 5mg', 'description' => 'Desloratadine 5mg tablet'],
            ['name' => 'Fexofenadine', 'description' => 'Second generation antihistamine'],
            ['name' => 'Fexofenadine 180mg', 'description' => 'Fexofenadine 180mg tablet'],
            ['name' => 'Levocetirizine', 'description' => 'Second generation antihistamine'],
            ['name' => 'Levocetirizine 5mg', 'description' => 'Levocetirizine 5mg tablet'],
            ['name' => 'Chlorpheniramine', 'description' => 'First generation antihistamine'],
            ['name' => 'Chlorpheniramine 4mg', 'description' => 'Chlorpheniramine 4mg tablet'],
            ['name' => 'Diphenhydramine', 'description' => 'First generation antihistamine'],
            ['name' => 'Diphenhydramine 25mg', 'description' => 'Diphenhydramine 25mg capsule'],
            ['name' => 'Diphenhydramine 50mg', 'description' => 'Diphenhydramine 50mg capsule'],
            ['name' => 'Promethazine', 'description' => 'First generation antihistamine'],
            ['name' => 'Promethazine 25mg', 'description' => 'Promethazine 25mg tablet'],
            ['name' => 'Hydroxyzine', 'description' => 'First generation antihistamine'],
            ['name' => 'Hydroxyzine 25mg', 'description' => 'Hydroxyzine 25mg tablet'],
            ['name' => 'Cyproheptadine', 'description' => 'First generation antihistamine'],
            ['name' => 'azelastine', 'description' => 'Antihistamine nasal spray'],
            ['name' => 'Olopatadine', 'description' => 'Antihistamine eye drops'],
            ['name' => 'Ventolin', 'description' => 'Brand name salbutamol'],
            ['name' => 'ProAir', 'description' => 'Brand name albuterol'],
            ['name' => 'Proventil', 'description' => 'Brand name albuterol'],
            ['name' => 'Xopenex', 'description' => 'Brand name levalbuterol'],
            ['name' => 'Symbicort', 'description' => 'Budesonide/formoterol combination'],
            ['name' => 'Advair', 'description' => 'Fluticasone/salmeterol combination'],
            ['name' => 'Dulera', 'description' => 'Mometasone/formoterol combination'],
            ['name' => 'Breo', 'description' => 'Fluticasone/vilanterol combination'],
            ['name' => 'Spiriva', 'description' => 'Brand name tiotropium'],
            ['name' => 'Incruse', 'description' => 'Brand name umeclidinium'],
            ['name' => 'Singulair', 'description' => 'Brand name montelukast'],
            ['name' => 'Zyrtec', 'description' => 'Brand name cetirizine'],
            ['name' => 'Claritin', 'description' => 'Brand name loratadine'],
            ['name' => 'Allegra', 'description' => 'Brand name fexofenadine'],
            ['name' => 'Benadryl', 'description' => 'Brand name diphenhydramine'],

            // Psychiatric / Neurological / Mental Health
            ['name' => 'Sertraline', 'description' => 'SSRI antidepressant'],
            ['name' => 'Sertraline 25mg', 'description' => 'Sertraline 25mg tablet'],
            ['name' => 'Sertraline 50mg', 'description' => 'Sertraline 50mg tablet'],
            ['name' => 'Sertraline 100mg', 'description' => 'Sertraline 100mg tablet'],
            ['name' => 'Fluoxetine', 'description' => 'SSRI antidepressant'],
            ['name' => 'Fluoxetine 20mg', 'description' => 'Fluoxetine 20mg capsule'],
            ['name' => 'Fluoxetine 40mg', 'description' => 'Fluoxetine 40mg capsule'],
            ['name' => 'Escitalopram', 'description' => 'SSRI antidepressant'],
            ['name' => 'Escitalopram 10mg', 'description' => 'Escitalopram 10mg tablet'],
            ['name' => 'Escitalopram 20mg', 'description' => 'Escitalopram 20mg tablet'],
            ['name' => 'Paroxetine', 'description' => 'SSRI antidepressant'],
            ['name' => 'Paroxetine 20mg', 'description' => 'Paroxetine 20mg tablet'],
            ['name' => 'Citalopram', 'description' => 'SSRI antidepressant'],
            ['name' => 'Citalopram 20mg', 'description' => 'Citalopram 20mg tablet'],
            ['name' => 'Venlafaxine', 'description' => 'SNRI antidepressant'],
            ['name' => 'Venlafaxine 75mg', 'description' => 'Venlafaxine 75mg tablet'],
            ['name' => 'Venlafaxine 150mg', 'description' => 'Venlafaxine 150mg tablet'],
            ['name' => 'Duloxetine', 'description' => 'SNRI antidepressant'],
            ['name' => 'Duloxetine 30mg', 'description' => 'Duloxetine 30mg capsule'],
            ['name' => 'Duloxetine 60mg', 'description' => 'Duloxetine 60mg capsule'],
            ['name' => 'Desvenlafaxine', 'description' => 'SNRI antidepressant'],
            ['name' => 'Milnacipran', 'description' => 'SNRI antidepressant'],
            ['name' => 'Bupropion', 'description' => 'NDRI antidepressant'],
            ['name' => 'Bupropion 150mg', 'description' => 'Bupropion 150mg tablet'],
            ['name' => 'Bupropion 300mg', 'description' => 'Bupropion 300mg tablet'],
            ['name' => 'Mirtazapine', 'description' => 'NaSSA antidepressant'],
            ['name' => 'Mirtazapine 15mg', 'description' => 'Mirtazapine 15mg tablet'],
            ['name' => 'Mirtazapine 30mg', 'description' => 'Mirtazapine 30mg tablet'],
            ['name' => 'Trazodone', 'description' => 'SARI antidepressant'],
            ['name' => 'Trazodone 50mg', 'description' => 'Trazodone 50mg tablet'],
            ['name' => 'Trazodone 100mg', 'description' => 'Trazodone 100mg tablet'],
            ['name' => 'Amitriptyline', 'description' => 'Tricyclic antidepressant'],
            ['name' => 'Amitriptyline 25mg', 'description' => 'Amitriptyline 25mg tablet'],
            ['name' => 'Amitriptyline 50mg', 'description' => 'Amitriptyline 50mg tablet'],
            ['name' => 'Nortriptyline', 'description' => 'Tricyclic antidepressant'],
            ['name' => 'Nortriptyline 25mg', 'description' => 'Nortriptyline 25mg capsule'],
            ['name' => 'Imipramine', 'description' => 'Tricyclic antidepressant'],
            ['name' => 'Clomipramine', 'description' => 'Tricyclic antidepressant'],
            ['name' => 'Alprazolam', 'description' => 'Benzodiazepine for anxiety'],
            ['name' => 'Alprazolam 0.25mg', 'description' => 'Alprazolam 0.25mg tablet'],
            ['name' => 'Alprazolam 0.5mg', 'description' => 'Alprazolam 0.5mg tablet'],
            ['name' => 'Alprazolam 1mg', 'description' => 'Alprazolam 1mg tablet'],
            ['name' => 'Lorazepam', 'description' => 'Benzodiazepine for anxiety'],
            ['name' => 'Lorazepam 0.5mg', 'description' => 'Lorazepam 0.5mg tablet'],
            ['name' => 'Lorazepam 1mg', 'description' => 'Lorazepam 1mg tablet'],
            ['name' => 'Lorazepam 2mg', 'description' => 'Lorazepam 2mg tablet'],
            ['name' => 'Diazepam', 'description' => 'Benzodiazepine for anxiety'],
            ['name' => 'Diazepam 5mg', 'description' => 'Diazepam 5mg tablet'],
            ['name' => 'Diazepam 10mg', 'description' => 'Diazepam 10mg tablet'],
            ['name' => 'Clonazepam', 'description' => 'Benzodiazepine for seizures/anxiety'],
            ['name' => 'Clonazepam 0.5mg', 'description' => 'Clonazepam 0.5mg tablet'],
            ['name' => 'Clonazepam 1mg', 'description' => 'Clonazepam 1mg tablet'],
            ['name' => 'Clonazepam 2mg', 'description' => 'Clonazepam 2mg tablet'],
            ['name' => 'Temazepam', 'description' => 'Benzodiazepine for sleep'],
            ['name' => 'Temazepam 10mg', 'description' => 'Temazepam 10mg tablet'],
            ['name' => 'Temazepam 20mg', 'description' => 'Temazepam 20mg tablet'],
            ['name' => 'Midazolam', 'description' => 'Benzodiazepine for sedation'],
            ['name' => 'Zolpidem', 'description' => 'Non-benzodiazepine for sleep'],
            ['name' => 'Zolpidem 5mg', 'description' => 'Zolpidem 5mg tablet'],
            ['name' => 'Zolpidem 10mg', 'description' => 'Zolpidem 10mg tablet'],
            ['name' => 'Eszopiclone', 'description' => 'Non-benzodiazepine for sleep'],
            ['name' => 'Zaleplon', 'description' => 'Non-benzodiazepine for sleep'],
            ['name' => 'Quetiapine', 'description' => 'Atypical antipsychotic'],
            ['name' => 'Quetiapine 25mg', 'description' => 'Quetiapine 25mg tablet'],
            ['name' => 'Quetiapine 100mg', 'description' => 'Quetiapine 100mg tablet'],
            ['name' => 'Quetiapine 200mg', 'description' => 'Quetiapine 200mg tablet'],
            ['name' => 'Risperidone', 'description' => 'Atypical antipsychotic'],
            ['name' => 'Risperidone 1mg', 'description' => 'Risperidone 1mg tablet'],
            ['name' => 'Risperidone 2mg', 'description' => 'Risperidone 2mg tablet'],
            ['name' => 'Olanzapine', 'description' => 'Atypical antipsychotic'],
            ['name' => 'Olanzapine 5mg', 'description' => 'Olanzapine 5mg tablet'],
            ['name' => 'Olanzapine 10mg', 'description' => 'Olanzapine 10mg tablet'],
            ['name' => 'Aripiprazole', 'description' => 'Atypical antipsychotic'],
            ['name' => 'Aripiprazole 10mg', 'description' => 'Aripiprazole 10mg tablet'],
            ['name' => 'Aripiprazole 15mg', 'description' => 'Aripiprazole 15mg tablet'],
            ['name' => 'Ziprasidone', 'description' => 'Atypical antipsychotic'],
            ['name' => 'Paliperidone', 'description' => 'Atypical antipsychotic'],
            ['name' => 'Clozapine', 'description' => 'Atypical antipsychotic'],
            ['name' => 'Haloperidol', 'description' => 'Typical antipsychotic'],
            ['name' => 'Haloperidol 5mg', 'description' => 'Haloperidol 5mg tablet'],
            ['name' => 'Lithium', 'description' => 'Mood stabilizer'],
            ['name' => 'Lithium 300mg', 'description' => 'Lithium 300mg tablet'],
            ['name' => 'Lithium 600mg', 'description' => 'Lithium 600mg tablet'],
            ['name' => 'Valproic Acid', 'description' => 'Mood stabilizer and anticonvulsant'],
            ['name' => 'Valproic Acid 250mg', 'description' => 'Valproic Acid 250mg capsule'],
            ['name' => 'Valproic Acid 500mg', 'description' => 'Valproic Acid 500mg tablet'],
            ['name' => 'Carbamazepine', 'description' => 'Anticonvulsant and mood stabilizer'],
            ['name' => 'Carbamazepine 200mg', 'description' => 'Carbamazepine 200mg tablet'],
            ['name' => 'Lamotrigine', 'description' => 'Anticonvulsant and mood stabilizer'],
            ['name' => 'Lamotrigine 25mg', 'description' => 'Lamotrigine 25mg tablet'],
            ['name' => 'Lamotrigine 100mg', 'description' => 'Lamotrigine 100mg tablet'],
            ['name' => 'Topiramate', 'description' => 'Anticonvulsant'],
            ['name' => 'Topiramate 25mg', 'description' => 'Topiramate 25mg tablet'],
            ['name' => 'Topiramate 50mg', 'description' => 'Topiramate 50mg tablet'],
            ['name' => 'Levetiracetam', 'description' => 'Anticonvulsant'],
            ['name' => 'Levetiracetam 500mg', 'description' => 'Levetiracetam 500mg tablet'],
            ['name' => 'Levetiracetam 1000mg', 'description' => 'Levetiracetam 1000mg tablet'],
            ['name' => 'Phenytoin', 'description' => 'Anticonvulsant'],
            ['name' => 'Phenytoin 100mg', 'description' => 'Phenytoin 100mg capsule'],
            ['name' => 'Phenobarbital', 'description' => 'Anticonvulsant and sedative'],
            ['name' => 'Zonisamide', 'description' => 'Anticonvulsant'],
            ['name' => 'Primidone', 'description' => 'Anticonvulsant'],
            ['name' => 'Lacosamide', 'description' => 'Anticonvulsant'],
            ['name' => 'Perampanel', 'description' => 'Anticonvulsant'],
            ['name' => 'Eslicarbazepine', 'description' => 'Anticonvulsant'],
            ['name' => 'Zoloft', 'description' => 'Brand name sertraline'],
            ['name' => 'Prozac', 'description' => 'Brand name fluoxetine'],
            ['name' => 'Lexapro', 'description' => 'Brand name escitalopram'],
            ['name' => 'Paxil', 'description' => 'Brand name paroxetine'],
            ['name' => 'Celexa', 'description' => 'Brand name citalopram'],
            ['name' => 'Effexor', 'description' => 'Brand name venlafaxine'],
            ['name' => 'Cymbalta', 'description' => 'Brand name duloxetine'],
            ['name' => 'Wellbutrin', 'description' => 'Brand name bupropion'],
            ['name' => 'Remeron', 'description' => 'Brand name mirtazapine'],
            ['name' => 'Xanax', 'description' => 'Brand name alprazolam'],
            ['name' => 'Ativan', 'description' => 'Brand name lorazepam'],
            ['name' => 'Valium', 'description' => 'Brand name diazepam'],
            ['name' => 'Klonopin', 'description' => 'Brand name clonazepam'],
            ['name' => 'Ambien', 'description' => 'Brand name zolpidem'],
            ['name' => 'Lunesta', 'description' => 'Brand name eszopiclone'],
            ['name' => 'Seroquel', 'description' => 'Brand name quetiapine'],
            ['name' => 'Risperdal', 'description' => 'Brand name risperidone'],
            ['name' => 'Zyprexa', 'description' => 'Brand name olanzapine'],
            ['name' => 'Abilify', 'description' => 'Brand name aripiprazole'],

            // Thyroid / Hormones
            ['name' => 'Levothyroxine', 'description' => 'Thyroid hormone replacement'],
            ['name' => 'Levothyroxine 25mcg', 'description' => 'Levothyroxine 25mcg tablet'],
            ['name' => 'Levothyroxine 50mcg', 'description' => 'Levothyroxine 50mcg tablet'],
            ['name' => 'Levothyroxine 75mcg', 'description' => 'Levothyroxine 75mcg tablet'],
            ['name' => 'Levothyroxine 100mcg', 'description' => 'Levothyroxine 100mcg tablet'],
            ['name' => 'Levothyroxine 125mcg', 'description' => 'Levothyroxine 125mcg tablet'],
            ['name' => 'Liothyronine', 'description' => 'Active thyroid hormone (T3)'],
            ['name' => 'Desiccated Thyroid', 'description' => 'Natural thyroid hormone'],
            ['name' => 'Methimazole', 'description' => 'Antithyroid medication'],
            ['name' => 'Methimazole 5mg', 'description' => 'Methimazole 5mg tablet'],
            ['name' => 'Propylthiouracil', 'description' => 'Antithyroid medication'],
            ['name' => 'Prednisone', 'description' => 'Corticosteroid'],
            ['name' => 'Prednisone 5mg', 'description' => 'Prednisone 5mg tablet'],
            ['name' => 'Prednisone 10mg', 'description' => 'Prednisone 10mg tablet'],
            ['name' => 'Prednisone 20mg', 'description' => 'Prednisone 20mg tablet'],
            ['name' => 'Prednisone 50mg', 'description' => 'Prednisone 50mg tablet'],
            ['name' => 'Hydrocortisone', 'description' => 'Corticosteroid'],
            ['name' => 'Hydrocortisone 10mg', 'description' => 'Hydrocortisone 10mg tablet'],
            ['name' => 'Hydrocortisone 20mg', 'description' => 'Hydrocortisone 20mg tablet'],
            ['name' => 'Methylprednisolone', 'description' => 'Corticosteroid'],
            ['name' => 'Methylprednisolone 4mg', 'description' => 'Methylprednisolone 4mg tablet'],
            ['name' => 'Dexamethasone', 'description' => 'Corticosteroid'],
            ['name' => 'Dexamethasone 0.5mg', 'description' => 'Dexamethasone 0.5mg tablet'],
            ['name' => 'Betamethasone', 'description' => 'Corticosteroid'],
            ['name' => 'Triamcinolone', 'description' => 'Corticosteroid'],
            ['name' => 'Budesonide', 'description' => 'Corticosteroid for IBD'],
            ['name' => 'Synthroid', 'description' => 'Brand name levothyroxine'],
            ['name' => 'Levoxyl', 'description' => 'Brand name levothyroxine'],
            ['name' => 'Unithroid', 'description' => 'Brand name levothyroxine'],
            ['name' => 'Cytomel', 'description' => 'Brand name liothyronine'],
            ['name' => 'Armour Thyroid', 'description' => 'Brand name desiccated thyroid'],
            ['name' => 'Deltasone', 'description' => 'Brand name prednisone'],
            ['name' => 'Solu-Cortef', 'description' => 'Brand name hydrocortisone injection'],

            // Vitamins & Supplements
            ['name' => 'Vitamin D3', 'description' => 'Vitamin D supplement (Cholecalciferol)'],
            ['name' => 'Vitamin D3 1000IU', 'description' => 'Vitamin D3 1000 IU'],
            ['name' => 'Vitamin D3 2000IU', 'description' => 'Vitamin D3 2000 IU'],
            ['name' => 'Vitamin D3 5000IU', 'description' => 'Vitamin D3 5000 IU'],
            ['name' => 'Vitamin D2', 'description' => 'Vitamin D supplement (Ergocalciferol)'],
            ['name' => 'Vitamin C', 'description' => 'Ascorbic acid supplement'],
            ['name' => 'Vitamin C 500mg', 'description' => 'Vitamin C 500mg tablet'],
            ['name' => 'Vitamin C 1000mg', 'description' => 'Vitamin C 1000mg tablet'],
            ['name' => 'Vitamin B1', 'description' => 'Thiamine supplement'],
            ['name' => 'Vitamin B2', 'description' => 'Riboflavin supplement'],
            ['name' => 'Vitamin B3', 'description' => 'Niacin supplement'],
            ['name' => 'Vitamin B6', 'description' => 'Pyridoxine supplement'],
            ['name' => 'Vitamin B6 25mg', 'description' => 'Vitamin B6 25mg tablet'],
            ['name' => 'Vitamin B12', 'description' => 'Cobalamin supplement'],
            ['name' => 'Vitamin B12 500mcg', 'description' => 'Vitamin B12 500mcg tablet'],
            ['name' => 'Vitamin B12 1000mcg', 'description' => 'Vitamin B12 1000mcg tablet'],
            ['name' => 'Vitamin B Complex', 'description' => 'B vitamin complex supplement'],
            ['name' => 'Folic Acid', 'description' => 'Folate supplement'],
            ['name' => 'Folic Acid 1mg', 'description' => 'Folic Acid 1mg tablet'],
            ['name' => 'Folic Acid 5mg', 'description' => 'Folic Acid 5mg tablet'],
            ['name' => 'Biotin', 'description' => 'Vitamin B7 supplement'],
            ['name' => 'Biotin 1000mcg', 'description' => 'Biotin 1000mcg tablet'],
            ['name' => 'Pantothenic Acid', 'description' => 'Vitamin B5 supplement'],
            ['name' => 'Vitamin A', 'description' => 'Retinol supplement'],
            ['name' => 'Vitamin E', 'description' => 'Tocopherol supplement'],
            ['name' => 'Vitamin K', 'description' => 'Phylloquinone supplement'],
            ['name' => 'Vitamin K2', 'description' => 'Menaquinone supplement'],
            ['name' => 'Multivitamin', 'description' => 'Multiple vitamin supplement'],
            ['name' => 'Calcium', 'description' => 'Calcium supplement'],
            ['name' => 'Calcium 500mg', 'description' => 'Calcium 500mg tablet'],
            ['name' => 'Calcium 600mg', 'description' => 'Calcium 600mg tablet'],
            ['name' => 'Calcium Carbonate', 'description' => 'Calcium supplement'],
            ['name' => 'Calcium Citrate', 'description' => 'Calcium supplement'],
            ['name' => 'Magnesium', 'description' => 'Magnesium supplement'],
            ['name' => 'Magnesium 250mg', 'description' => 'Magnesium 250mg tablet'],
            ['name' => 'Magnesium 400mg', 'description' => 'Magnesium 400mg tablet'],
            ['name' => 'Magnesium Oxide', 'description' => 'Magnesium supplement'],
            ['name' => 'Magnesium Citrate', 'description' => 'Magnesium supplement'],
            ['name' => 'Magnesium Glycinate', 'description' => 'Magnesium supplement'],
            ['name' => 'Iron', 'description' => 'Iron supplement'],
            ['name' => 'Iron 65mg', 'description' => 'Iron 65mg tablet (Ferrous sulfate)'],
            ['name' => 'Iron 325mg', 'description' => 'Iron 325mg tablet (Ferrous sulfate)'],
            ['name' => 'Ferrous Gluconate', 'description' => 'Iron supplement'],
            ['name' => 'Ferrous Fumarate', 'description' => 'Iron supplement'],
            ['name' => 'Polysaccharide Iron', 'description' => 'Iron supplement'],
            ['name' => 'Iron Polymaltose', 'description' => 'Iron supplement'],
            ['name' => 'Zinc', 'description' => 'Zinc supplement'],
            ['name' => 'Zinc 30mg', 'description' => 'Zinc 30mg tablet'],
            ['name' => 'Zinc 50mg', 'description' => 'Zinc 50mg tablet'],
            ['name' => 'Zinc Gluconate', 'description' => 'Zinc supplement'],
            ['name' => 'Copper', 'description' => 'Copper supplement'],
            ['name' => 'Selenium', 'description' => 'Selenium supplement'],
            ['name' => 'Selenium 200mcg', 'description' => 'Selenium 200mcg tablet'],
            ['name' => 'Chromium', 'description' => 'Chromium supplement'],
            ['name' => 'Chromium 200mcg', 'description' => 'Chromium 200mcg tablet'],
            ['name' => 'Manganese', 'description' => 'Manganese supplement'],
            ['name' => 'Potassium', 'description' => 'Potassium supplement'],
            ['name' => 'Potassium 99mg', 'description' => 'Potassium 99mg tablet'],
            ['name' => 'Potassium Chloride', 'description' => 'Potassium supplement'],
            ['name' => 'Potassium Chloride 600mg', 'description' => 'Potassium chloride 600mg tablet'],
            ['name' => 'Omega-3 Fish Oil', 'description' => 'Omega-3 fatty acid supplement'],
            ['name' => 'Omega-3 1000mg', 'description' => 'Omega-3 fish oil 1000mg'],
            ['name' => 'Omega-3 1200mg', 'description' => 'Omega-3 fish oil 1200mg'],
            ['name' => 'Fish Oil', 'description' => 'Fish oil supplement'],
            ['name' => 'Cod Liver Oil', 'description' => 'Fish oil supplement'],
            ['name' => 'Krill Oil', 'description' => 'Omega-3 supplement'],
            ['name' => 'Flaxseed Oil', 'description' => 'Omega-3 supplement'],
            ['name' => 'Coenzyme Q10', 'description' => 'CoQ10 supplement'],
            ['name' => 'CoQ10 100mg', 'description' => 'Coenzyme Q10 100mg'],
            ['name' => 'CoQ10 200mg', 'description' => 'Coenzyme Q10 200mg'],
            ['name' => 'Alpha Lipoic Acid', 'description' => 'Antioxidant supplement'],
            ['name' => 'Alpha Lipoic Acid 300mg', 'description' => 'Alpha lipoic acid 300mg'],
            ['name' => 'Glucosamine', 'description' => 'Joint supplement'],
            ['name' => 'Glucosamine 500mg', 'description' => 'Glucosamine 500mg tablet'],
            ['name' => 'Glucosamine Sulfate', 'description' => 'Joint supplement'],
            ['name' => 'Chondroitin', 'description' => 'Joint supplement'],
            ['name' => 'Chondroitin Sulfate', 'description' => 'Joint supplement'],
            ['name' => 'MSM', 'description' => 'Methylsulfonylmethane supplement'],
            ['name' => 'Glucosamine Chondroitin', 'description' => 'Joint supplement combination'],
            ['name' => 'Collagen', 'description' => 'Collagen supplement'],
            ['name' => 'Probiotic', 'description' => 'Probiotic supplement'],
            ['name' => 'Probiotic 10B', 'description' => 'Probiotic 10 billion CFU'],
            ['name' => 'Probiotic 50B', 'description' => 'Probiotic 50 billion CFU'],
            ['name' => 'Digestive Enzyme', 'description' => 'Digestive enzyme supplement'],
            ['name' => 'Melatonin', 'description' => 'Sleep supplement'],
            ['name' => 'Melatonin 1mg', 'description' => 'Melatonin 1mg tablet'],
            ['name' => 'Melatonin 3mg', 'description' => 'Melatonin 3mg tablet'],
            ['name' => 'Melatonin 5mg', 'description' => 'Melatonin 5mg tablet'],
            ['name' => 'Melatonin 10mg', 'description' => 'Melatonin 10mg tablet'],
            ['name' => '5-HTP', 'description' => '5-Hydroxytryptophan supplement'],
            ['name' => 'GABA', 'description' => 'GABA supplement'],
            ['name' => 'L-Theanine', 'description' => 'Amino acid supplement'],
            ['name' => 'L-Tyrosine', 'description' => 'Amino acid supplement'],
            ['name' => 'L-Glutamine', 'description' => 'Amino acid supplement'],
            ['name' => 'L-Carnitine', 'description' => 'Amino acid supplement'],
            ['name' => 'L-Carnitine 500mg', 'description' => 'L-Carnitine 500mg tablet'],
            ['name' => 'BCAA', 'description' => 'Branched chain amino acids'],
            ['name' => 'Creatine', 'description' => 'Creatine monohydrate supplement'],
            ['name' => 'Ashwagandha', 'description' => 'Adaptogenic herb supplement'],
            ['name' => 'Ashwagandha 300mg', 'description' => 'Ashwagandha 300mg capsule'],
            ['name' => 'Turmeric', 'description' => 'Turmeric/Curcumin supplement'],
            ['name' => 'Turmeric 500mg', 'description' => 'Turmeric 500mg capsule'],
            ['name' => 'Curcumin', 'description' => 'Curcumin supplement'],
            ['name' => 'Ginger', 'description' => 'Ginger supplement'],
            ['name' => 'Ginkgo Biloba', 'description' => 'Herbal supplement'],
            ['name' => 'St. John\'s Wort', 'description' => 'Herbal supplement'],
            ['name' => 'Valerian Root', 'description' => 'Herbal sleep supplement'],
            ['name' => 'Milk Thistle', 'description' => 'Herbal liver supplement'],
            ['name' => 'Saw Palmetto', 'description' => 'Herbal supplement for prostate'],
            ['name' => 'Pycnogenol', 'description' => 'Pine bark extract supplement'],
            ['name' => 'Resveratrol', 'description' => 'Antioxidant supplement'],
            ['name' => 'Quercetin', 'description' => 'Antioxidant supplement'],
            ['name' => 'Berberine', 'description' => 'Herbal supplement'],
            ['name' => 'Cissus Quadrangularis', 'description' => 'Herbal supplement'],
            ['name' => 'D3 drops', 'description' => 'Vitamin D3 liquid drops'],
            ['name' => 'Vitamin D drops', 'description' => 'Vitamin D liquid drops for infants'],
            ['name' => 'Ferrosach', 'description' => 'Iron supplement (Ferrous sulfate)'],
            ['name' => 'Ferinject', 'description' => 'Iron supplement (IV)'],
            ['name' => 'Fefol', 'description' => 'Iron and folic acid supplement'],
            ['name' => 'Pregnacare', 'description' => 'Prenatal vitamin'],
            ['name' => 'Centrum', 'description' => 'Brand name multivitamin'],
            ['name' => 'One A Day', 'description' => 'Brand name multivitamin'],
            ['name' => 'Nature Made', 'description' => 'Brand name vitamins'],
            ['name' => 'Garden of Life', 'description' => 'Brand name vitamins'],
            ['name' => 'Nordic Naturals', 'description' => 'Brand name fish oil'],
            ['name' => 'Now Foods', 'description' => 'Brand name supplements'],
            ['name' => 'Optimum Nutrition', 'description' => 'Brand name supplements'],
            ['name' => ' Thorne', 'description' => 'Brand name supplements'],

            // Eye / ENT
            ['name' => 'Timolol', 'description' => 'Beta blocker eye drops for glaucoma'],
            ['name' => 'Timolol 0.5%', 'description' => 'Timolol 0.5% eye drops'],
            ['name' => 'Latanoprost', 'description' => 'Prostaglandin eye drops for glaucoma'],
            ['name' => 'Latanoprost 0.005%', 'description' => 'Latanoprost 0.005% eye drops'],
            ['name' => 'Bimatoprost', 'description' => 'Prostaglandin eye drops'],
            ['name' => 'Travoprost', 'description' => 'Prostaglandin eye drops'],
            ['name' => 'Dorzolamide', 'description' => 'Carbonic anhydrase inhibitor eye drops'],
            ['name' => 'Brinzolamide', 'description' => 'Carbonic anhydrase inhibitor eye drops'],
            ['name' => 'Brimonidine', 'description' => 'Alpha agonist eye drops'],
            ['name' => 'Brimonidine 0.2%', 'description' => 'Brimonidine 0.2% eye drops'],
            ['name' => 'Ketorolac', 'description' => 'NSAID eye drops'],
            ['name' => 'Ketorolac 0.5%', 'description' => 'Ketorolac 0.5% eye drops'],
            ['name' => 'Diclofenac eye drops', 'description' => 'NSAID eye drops'],
            ['name' => 'Naphazoline', 'description' => 'Redness relief eye drops'],
            ['name' => 'Tetrahydrozoline', 'description' => 'Redness relief eye drops'],
            ['name' => 'Carboxymethylcellulose', 'description' => 'Artificial tears'],
            ['name' => 'Hydroxypropyl Methylcellulose', 'description' => 'Artificial tears'],
            ['name' => 'Polyethylene glycol eye drops', 'description' => 'Artificial tears'],
            ['name' => 'Prednisolone eye drops', 'description' => 'Corticosteroid eye drops'],
            ['name' => 'Prednisolone acetate 1%', 'description' => 'Prednisolone 1% eye drops'],
            ['name' => 'Fluorometholone', 'description' => 'Corticosteroid eye drops'],
            ['name' => 'Loteprednol', 'description' => 'Corticosteroid eye drops'],
            ['name' => 'Ciprofloxacin eye drops', 'description' => 'Antibiotic eye drops'],
            ['name' => 'Ofloxacin eye drops', 'description' => 'Antibiotic eye drops'],
            ['name' => 'Gentamicin eye drops', 'description' => 'Antibiotic eye drops'],
            ['name' => 'Tobramycin eye drops', 'description' => 'Antibiotic eye drops'],
            ['name' => 'Neomycin eye drops', 'description' => 'Antibiotic eye drops'],
            ['name' => 'Polymyxin B eye drops', 'description' => 'Antibiotic eye drops'],
            ['name' => 'Erythromycin eye ointment', 'description' => 'Antibiotic eye ointment'],
            ['name' => 'Tetracycline eye ointment', 'description' => 'Antibiotic eye ointment'],
            ['name' => 'Acyclovir eye ointment', 'description' => 'Antiviral eye ointment'],
            ['name' => 'Atropine eye drops', 'description' => 'Cycloplegic eye drops'],
            ['name' => 'Cyclopentolate', 'description' => 'Cycloplegic eye drops'],
            ['name' => 'Tropicamide', 'description' => 'Cycloplegic eye drops'],
            ['name' => 'Phenylephrine eye drops', 'description' => 'Mydriatic eye drops'],
            ['name' => 'Sodium chloride eye drops', 'description' => 'Hypertonic saline eye drops'],
            ['name' => 'Xylometazoline nasal spray', 'description' => 'Nasal decongestant'],
            ['name' => 'Oxymetazoline nasal spray', 'description' => 'Nasal decongestant'],
            ['name' => 'Phenylephrine nasal spray', 'description' => 'Nasal decongestant'],
            ['name' => 'Sodium chloride nasal spray', 'description' => 'Saline nasal spray'],
            ['name' => 'Fluticasone nasal spray', 'description' => 'Corticosteroid nasal spray'],
            ['name' => 'Fluticasone 50mcg', 'description' => 'Fluticasone nasal spray'],
            ['name' => 'Budesonide nasal spray', 'description' => 'Corticosteroid nasal spray'],
            ['name' => 'Mometasone nasal spray', 'description' => 'Corticosteroid nasal spray'],
            ['name' => 'Beclomethasone nasal spray', 'description' => 'Corticosteroid nasal spray'],
            ['name' => 'Cetirizine nasal spray', 'description' => 'Antihistamine nasal spray'],
            ['name' => 'Azelastine nasal spray', 'description' => 'Antihistamine nasal spray'],
            ['name' => 'Ipratropium nasal spray', 'description' => 'Anticholinergic nasal spray'],
            ['name' => 'Saline nasal spray', 'description' => 'Salt water nasal spray'],
            ['name' => 'Xylocaine spray', 'description' => 'Lidocaine spray for throat'],
            ['name' => 'StellTIM', 'description' => 'Brand name timolol eye drops'],
            ['name' => 'Xalatan', 'description' => 'Brand name latanoprost eye drops'],
            ['name' => 'Lumigan', 'description' => 'Brand name bimatoprost eye drops'],
            ['name' => 'Travatan', 'description' => 'Brand name travoprost eye drops'],
            ['name' => 'Trusopt', 'description' => 'Brand name dorzolamide eye drops'],
            ['name' => 'Azopt', 'description' => 'Brand name brinzolamide eye drops'],
            ['name' => 'Combigan', 'description' => 'Brimonidine/timolol combination eye drops'],
            ['name' => 'Refresh Tears', 'description' => 'Brand name artificial tears'],
            ['name' => 'Systane', 'description' => 'Brand name artificial tears'],
            ['name' => 'TheraTears', 'description' => 'Brand name artificial tears'],
            ['name' => 'Visine', 'description' => 'Brand name eye drops'],
            ['name' => 'Zaditor', 'description' => 'Brand name ketotifen eye drops'],
            ['name' => 'Claritin Eye', 'description' => 'Brand name ketotifen eye drops'],
            ['name' => 'Afrin', 'description' => 'Brand name oxymetazoline nasal spray'],
            ['name' => 'Flixonase', 'description' => 'Brand name fluticasone nasal spray'],
            ['name' => 'Nasonex', 'description' => 'Brand name mometasone nasal spray'],
            ['name' => 'Rhinocort', 'description' => 'Brand name budesonide nasal spray'],

            // Dermatological / Skin
            ['name' => 'Hydrocortisone cream 1%', 'description' => 'Mild corticosteroid cream'],
            ['name' => 'Hydrocortisone cream', 'description' => 'Mild corticosteroid cream'],
            ['name' => 'Hydrocortisone 2.5%', 'description' => 'Moderate corticosteroid cream'],
            ['name' => 'Betamethasone cream', 'description' => 'Strong corticosteroid cream'],
            ['name' => 'Betamethasone 0.05%', 'description' => 'Betamethasone cream 0.05%'],
            ['name' => 'Betamethasone 0.1%', 'description' => 'Betamethasone cream 0.1%'],
            ['name' => 'Clobetasol cream', 'description' => 'Very strong corticosteroid cream'],
            ['name' => 'Clobetasol 0.05%', 'description' => 'Clobetasol 0.05% cream'],
            ['name' => 'Triamcinolone cream', 'description' => 'Corticosteroid cream'],
            ['name' => 'Triamcinolone 0.1%', 'description' => 'Triamcinolone 0.1% cream'],
            ['name' => 'Triamcinolone 0.025%', 'description' => 'Triamcinolone 0.025% cream'],
            ['name' => 'Mometasone cream', 'description' => 'Corticosteroid cream'],
            ['name' => 'Mometasone 0.1%', 'description' => 'Mometasone 0.1% cream'],
            ['name' => 'Fluticasone cream', 'description' => 'Corticosteroid cream'],
            ['name' => 'Desonide cream', 'description' => 'Mild corticosteroid cream'],
            ['name' => 'Fluocinonide cream', 'description' => 'Strong corticosteroid cream'],
            ['name' => 'Halcinonide cream', 'description' => 'Very strong corticosteroid cream'],
            ['name' => 'Dexamethasone cream', 'description' => 'Corticosteroid cream'],
            ['name' => 'Methylprednisolone cream', 'description' => 'Corticosteroid cream'],
            ['name' => 'Clindamycin gel', 'description' => 'Antibiotic for acne'],
            ['name' => 'Clindamycin 1%', 'description' => 'Clindamycin 1% gel'],
            ['name' => 'Erythromycin gel', 'description' => 'Antibiotic for acne'],
            ['name' => 'Erythromycin 2%', 'description' => 'Erythromycin 2% solution'],
            ['name' => 'Benzoyl peroxide', 'description' => 'Acne treatment'],
            ['name' => 'Benzoyl peroxide 2.5%', 'description' => 'Benzoyl peroxide 2.5% gel'],
            ['name' => 'Benzoyl peroxide 5%', 'description' => 'Benzoyl peroxide 5% gel'],
            ['name' => 'Benzoyl peroxide 10%', 'description' => 'Benzoyl peroxide 10% gel'],
            ['name' => 'Salicylic acid', 'description' => 'Acne treatment'],
            ['name' => 'Salicylic acid 2%', 'description' => 'Salicylic acid 2% solution'],
            ['name' => 'Adapalene', 'description' => 'Retinoid for acne'],
            ['name' => 'Adapalene 0.1%', 'description' => 'Adapalene 0.1% gel'],
            ['name' => 'Adapalene 0.3%', 'description' => 'Adapalene 0.3% gel'],
            ['name' => 'Tretinoin', 'description' => 'Retinoid for acne and anti-aging'],
            ['name' => 'Tretinoin 0.025%', 'description' => 'Tretinoin 0.025% cream'],
            ['name' => 'Tretinoin 0.05%', 'description' => 'Tretinoin 0.05% cream'],
            ['name' => 'Tretinoin 0.1%', 'description' => 'Tretinoin 0.1% cream'],
            ['name' => 'Isotretinoin', 'description' => 'Oral retinoid for severe acne'],
            ['name' => 'Isotretinoin 10mg', 'description' => 'Isotretinoin 10mg capsule'],
            ['name' => 'Isotretinoin 20mg', 'description' => 'Isotretinoin 20mg capsule'],
            ['name' => 'Tazarotene', 'description' => 'Retinoid for psoriasis and acne'],
            ['name' => 'Tazarotene 0.1%', 'description' => 'Tazarotene 0.1% cream'],
            ['name' => 'Dapsone gel', 'description' => 'Antibiotic for acne'],
            ['name' => 'Azelaic acid', 'description' => 'Acne treatment'],
            ['name' => 'Azelaic acid 15%', 'description' => 'Azelaic acid 15% gel'],
            ['name' => 'Sulfacetamide', 'description' => 'Antibiotic for acne and rosacea'],
            ['name' => 'Mupirocin', 'description' => 'Antibiotic skin ointment'],
            ['name' => 'Mupirocin 2%', 'description' => 'Mupirocin 2% ointment'],
            ['name' => 'Fusidic acid', 'description' => 'Antibiotic skin cream'],
            ['name' => 'Retapamulin', 'description' => 'Antibiotic skin ointment'],
            ['name' => 'Ciclopirox', 'description' => 'Antifungal nail lacquer'],
            ['name' => 'Ciclopirox 8%', 'description' => 'Ciclopirox 8% nail lacquer'],
            ['name' => 'Terbinafine cream', 'description' => 'Antifungal cream'],
            ['name' => 'Terbinafine 1%', 'description' => 'Terbinafine 1% cream'],
            ['name' => 'Clotrimazole cream', 'description' => 'Antifungal cream'],
            ['name' => 'Clotrimazole 1%', 'description' => 'Clotrimazole 1% cream'],
            ['name' => 'Miconazole cream', 'description' => 'Antifungal cream'],
            ['name' => 'Miconazole 2%', 'description' => 'Miconazole 2% cream'],
            ['name' => 'Ketoconazole cream', 'description' => 'Antifungal cream'],
            ['name' => 'Ketoconazole 2%', 'description' => 'Ketoconazole 2% cream'],
            ['name' => 'Econazole cream', 'description' => 'Antifungal cream'],
            ['name' => 'Sertaconazole cream', 'description' => 'Antifungal cream'],
            ['name' => 'Butenafine cream', 'description' => 'Antifungal cream'],
            ['name' => 'Tolnaftate cream', 'description' => 'Antifungal cream'],
            ['name' => 'Undecylenic acid', 'description' => 'Antifungal agent'],
            ['name' => 'Acyclovir cream', 'description' => 'Antiviral cream for herpes'],
            ['name' => 'Acyclovir 5%', 'description' => 'Acyclovir 5% cream'],
            ['name' => 'Penciclovir cream', 'description' => 'Antiviral cream for herpes'],
            ['name' => 'Penciclovir 1%', 'description' => 'Penciclovir 1% cream'],
            ['name' => 'Imiquimod cream', 'description' => 'Immune response modifier'],
            ['name' => 'Imiquimod 5%', 'description' => 'Imiquimod 5% cream'],
            ['name' => '5-Fluorouracil cream', 'description' => 'Chemotherapy cream for actinic keratosis'],
            ['name' => '5-FU cream', 'description' => '5-Fluorouracil cream'],
            ['name' => 'Ingenol mebutate', 'description' => 'Treatment for actinic keratosis'],
            ['name' => 'Diclofenac gel', 'description' => 'NSAID gel for pain'],
            ['name' => 'Diclofenac 1%', 'description' => 'Diclofenac 1% gel'],
            ['name' => 'Piroxicam gel', 'description' => 'NSAID gel'],
            ['name' => 'Ketoprofen gel', 'description' => 'NSAID gel'],
            ['name' => 'Ibuprofen gel', 'description' => 'NSAID gel'],
            ['name' => 'Lidocaine gel', 'description' => 'Local anesthetic gel'],
            ['name' => 'Lidocaine 2%', 'description' => 'Lidocaine 2% gel'],
            ['name' => 'Lidocaine 5%', 'description' => 'Lidocaine 5% gel'],
            ['name' => 'Prilocaine cream', 'description' => 'Local anesthetic cream'],
            ['name' => 'EMLA cream', 'description' => 'Lidocaine/prilocaine cream'],
            ['name' => 'Capsaicin cream', 'description' => 'Pain relief cream'],
            ['name' => 'Capsaicin 0.025%', 'description' => 'Capsaicin 0.025% cream'],
            ['name' => 'Capsaicin 0.075%', 'description' => 'Capsaicin 0.075% cream'],
            ['name' => 'Camphor cream', 'description' => 'Topical analgesic'],
            ['name' => 'Menthol gel', 'description' => 'Topical analgesic'],
            ['name' => 'Moisturizing cream', 'description' => 'Skin moisturizer'],
            ['name' => 'CeraVe', 'description' => 'Moisturizing cream brand'],
            ['name' => 'Cetaphil', 'description' => 'Skin care brand'],
            ['name' => 'Aquaphor', 'description' => 'Skin ointment'],
            ['name' => 'Vaseline', 'description' => 'Petrolatum jelly'],
            ['name' => 'Calamine lotion', 'description' => 'Skin lotion for itch'],
            ['name' => 'Calamine', 'description' => 'Calamine lotion'],
            ['name' => 'Soolantra', 'description' => 'Brand name ivermectin cream for rosacea'],
            ['name' => 'Metrogel', 'description' => 'Brand name metronidazole gel'],
            ['name' => 'Dovonex', 'description' => 'Brand name calcipotriene cream'],
            ['name' => 'Taclonex', 'description' => 'Calcipotriene/betamethasone combination'],
            ['name' => 'Enbrel', 'description' => 'Brand name etanercept injection'],
            ['name' => 'Humira', 'description' => 'Brand name adalimumab injection'],
            ['name' => 'Stelara', 'description' => 'Brand name ustekinumab injection'],
            ['name' => 'Dupixent', 'description' => 'Brand name dupilumab injection'],
        ];

        foreach ($categories as $category) {
            MedicineCategory::create($category);
        }
    }
}
